import React, { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

export type LanguageCode = 'en' | 'hi' | 'bn' | 'te' | 'mr' | 'ta' | 'gu' | 'kn' | 'ml';

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    govIndia: 'GOVERNMENT OF INDIA',
    ministry: 'Ministry of Commerce and Industry',
    portalTagline: 'National Public Procurement Portal',
    skipToMain: 'Skip to Main Content',
    raiseTicket: 'Raise a Ticket',
    needHelp: 'Need Help ?',
    fontSize: 'Font Size',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    gemTitle: 'Government e Marketplace',
    gemMotto: 'Efficient • Transparent • Inclusive',
    searchPlaceholder: 'Looking for something on GeM?',
    products: 'PRODUCTS',
    services: 'SERVICES',
    content: 'CONTENT',
    courses: 'INTERACTIVE TRAINING COURSES',
    forwardAuction: 'Forward Auction',
    bids: 'Bids',
    signUp: 'Sign Up',
    login: 'Login',
    aiEngine: '⚡ AI Statutory Engine',
    categories: 'Categories',
    home: 'Home',
    features: 'Features & Benefits',
    sellerOnGem: 'Seller on GeM',
    viewContracts: 'View Contracts',
    cppp: 'CPPP',
    heroDecade: 'A Decade of Trust',
    heroDecadeSub: '& Transformation',
    heroMotto: 'A Decade of Boundless Opportunities',
    heroCelebrate: 'Celebrating a decade that empowered opportunities and fueled national growth',
    heroSub2: 'Come, be a part of this transformative journey',
    askGemmy: 'Ask GeMMy',
    askGemmySub: '(Powered by AI)',
    sellerDesk: 'Seller Compliance Desk',
    officerPortal: 'Procurement Officer Portal',
    gmv: 'Gross Merchandise Value',
    ordersProcessed: 'Orders Processed',
    registeredSellers: 'Registered Sellers',
    primaryBuyers: 'Verified Primary Buyers',
    vocalForLocal: '#vocalforlocal',
    gemOutlets: 'GeM Outlet Stores',
    popularProducts: 'POPULAR PRODUCT CATEGORIES',
    popularServices: 'POPULAR SERVICE CATEGORIES',
    whyChooseGem: 'Why you should choose GeM',
    customersSpeak: 'Customers Speak',
    exploreMarket: 'EXPLORE THE MARKET',
    viewAllServices: 'VIEW ALL SERVICES',
    footerRuleNotice: 'Statutory Compliance & GFR Rule 144(xi) Verification Gateway',
    footerCopyright: '© 2026 Government e Marketplace (GeM). Smart India Hackathon Prototype (SIH26100).',
    activeTenders: 'Active Tenders',
    compareBidders: 'Compare Bidders',
    deepAudit: 'Deep Audit',
    findingsRisk: 'Findings & Risk',
    auditSignOff: 'Audit & Final Sign-Off',
    dashboard: 'Dashboard',
    officerConsole: 'Procurement Officer Scrutiny Console',
    sellerPortal: 'Seller Compliance Self-Service Portal',
    logout: 'Logout',
    gemHome: 'GeM Home',
    close: 'Close',
    submit: 'Submit',
    cancel: 'Cancel',
    readiness: 'Compliance Readiness',
    verified: 'Verified',
    pending: 'Pending',
    issues: 'Issues',
    discrepancies: 'Discrepancies Flagged',
    activeProcurementTenders: 'Active Procurement Tenders',
    activeTendersSub: 'Live monitoring of tender bids and automated compliance ingestion.',
    bidsUnderScrutiny: 'Bids Under Scrutiny',
    aiScannedBids: 'AI Scanned Bids',
    tenderRefNo: 'Tender Ref No.',
    description: 'Description',
    bidders: 'Bidders',
    aiScrutinyStatus: 'AI Scrutiny Status',
    action: 'Action',
    compareBiddersBtn: 'Compare Bidders >',
    comparativeScrutiny: 'Comparative Bidder Scrutiny',
    rankBidderName: 'Rank / Bidder Name',
    complianceScore: 'Compliance Score',
    riskLevel: 'Risk Level',
    statutoryParity: 'Statutory Parity',
    localContent: 'MII Local Content',
    detailAudit: 'Detail Audit',
    lowRisk: 'LOW',
    mediumRisk: 'MEDIUM',
    highRisk: 'HIGH',
    backToTenders: '< Back to Tenders',
    backToComparison: '< Back to Comparison',
    backToDetail: '< Back to Detail',
    backToScrutiny: '< Back to Scrutiny',
    statutoryVerification: 'Statutory Verification',
    tenderVerification: 'Tender-Specific Verification',
    inspect: 'Inspect',
    explainableRisk: 'Explainable Risk & Compliance Score',
    trafficLightTier: 'Traffic Light Tier',
    factor: 'Factor',
    weight: 'Assigned Weight',
    result: 'Result',
    verdict: 'Verdict',
    auditTrailTitle: 'Complete Verification Audit Trail & Official Sign-Off Gate',
    verificationTimeline: 'Verification Timeline',
    auditTrailTable: 'Audit Trail Table',
    timestamp: 'Timestamp',
    check: 'Check',
    source: 'Source',
    evidence: 'Evidence',
    performedBy: 'Performed By',
    finalDecision: 'Final Decision — Procurement Officer',
    committeeRemarks: 'Official Committee Scrutiny Remarks',
    approveQualify: 'Approve / Qualify',
    sendClarification: 'Send for Clarification',
    rejectDisqualify: 'Reject / Disqualify',
    exportDossier: 'Export Audit Dossier (.json)',
    uploadMissing: 'Upload Missing Document',
    runAiExtraction: 'Run AI Extraction & Cross-Check',
    signSubmitBid: 'Sign & Submit Bid on GeM',
    updateInfo: 'Update Information & Re-verify',
    enterArn: 'Enter Valid GSTR-3B ARN',
    ready: 'Ready',
    attentionReq: 'Attention Req.',
    portalStatus: 'Portal Verification Status (Live Statutory API Feeds)',
  },
  hi: {
    govIndia: 'भारत सरकार',
    ministry: 'वाणिज्य एवं उद्योग मंत्रालय',
    portalTagline: 'राष्ट्रीय सार्वजनिक खरीद पोर्टल',
    skipToMain: 'मुख्य सामग्री पर जाएं',
    raiseTicket: 'शिकायत दर्ज करें',
    needHelp: 'सहायता चाहिए ?',
    fontSize: 'फ़ॉन्ट आकार',
    darkMode: 'डार्क मोड',
    lightMode: 'लाइट मोड',
    gemTitle: 'गवर्नमेंट ई मार्केटप्लेस',
    gemMotto: 'दक्ष • पारदर्शी • समावेशी',
    searchPlaceholder: 'GeM पर आप क्या खोजना चाहते हैं?',
    products: 'उत्पाद',
    services: 'सेवाएं',
    content: 'सामग्री',
    courses: 'प्रशिक्षण पाठ्यक्रम',
    forwardAuction: 'अग्रिम नीलामी',
    bids: 'बोलियां',
    signUp: 'साइन अप',
    login: 'लॉग इन',
    aiEngine: '⚡ एआई सांविधिक इंजन',
    categories: 'श्रेणियां',
    home: 'होम',
    features: 'सुविधाएं व लाभ',
    sellerOnGem: 'GeM पर विक्रेता',
    viewContracts: 'अनुबंध देखें',
    cppp: 'सीपीपीपी',
    heroDecade: 'भरोसे और बदलाव',
    heroDecadeSub: 'का दशक',
    heroMotto: 'असीम संभावनाओं का दशक',
    heroCelebrate: 'उत्सव उस दशक का जिसने अवसरों को नई उड़ान दी',
    heroSub2: 'आइए, इस परिवर्तनकारी यात्रा का हिस्सा बनें',
    askGemmy: 'GeMMy से पूछें',
    askGemmySub: '(एआई संचालित)',
    sellerDesk: 'विक्रेता अनुपालन डेस्क',
    officerPortal: 'खरीद अधिकारी पोर्टल',
    gmv: 'सकल व्यापारिक मूल्य',
    ordersProcessed: 'संसाधित ऑर्डर',
    registeredSellers: 'पंजीकृत विक्रेता',
    primaryBuyers: 'सत्यापित प्राथमिक खरीदार',
    vocalForLocal: '#vocalforlocal',
    gemOutlets: 'GeM आउटलेट स्टोर्स',
    popularProducts: 'लोकप्रिय उत्पाद श्रेणियां',
    popularServices: 'लोकप्रिय सेवा श्रेणियां',
    whyChooseGem: 'आपको GeM क्यों चुनना चाहिए',
    customersSpeak: 'ग्राहक विचार',
    exploreMarket: 'बाजार का अन्वेषण करें',
    viewAllServices: 'सभी सेवाएं देखें',
    footerRuleNotice: 'सांविधिक अनुपालन और जीएफआर नियम 144(xi) सत्यापन गेटवे',
    footerCopyright: '© 2026 गवर्नमेंट ई मार्केटप्लेस (GeM). स्मार्ट इंडिया हैकाथॉन प्रोटोटाइप (SIH26100).',
    activeTenders: 'सक्रिय निविदाएं',
    compareBidders: 'बोलीदाताओं की तुलना',
    deepAudit: 'गहन ऑडिट',
    findingsRisk: 'निष्कर्ष और जोखिम',
    auditSignOff: 'ऑडिट और अंतिम निर्णय',
    dashboard: 'डैशबोर्ड',
    officerConsole: 'खरीद अधिकारी जांच कंसोल',
    sellerPortal: 'विक्रेता अनुपालन पोर्टल',
    logout: 'लॉगआउट',
    gemHome: 'GeM होम',
    close: 'बंद करें',
    submit: 'जमा करें',
    cancel: 'रद्द करें',
    readiness: 'अनुपालन तत्परता',
    verified: 'सत्यापित',
    pending: 'लंबित',
    issues: 'समस्याएं',
    discrepancies: 'विसंगतियां ध्वजांकित',
    activeProcurementTenders: 'सक्रिय खरीद निविदाएं',
    activeTendersSub: 'निविदा बोलियों की लाइव निगरानी और स्वचालित अनुपालन विश्लेषण।',
    bidsUnderScrutiny: 'जांच के अधीन बोलियां',
    aiScannedBids: 'एआई द्वारा स्कैन की गई बोलियां',
    tenderRefNo: 'निविदा संदर्भ संख्या',
    description: 'विवरण',
    bidders: 'बोलीदाता',
    aiScrutinyStatus: 'एआई जांच स्थिति',
    action: 'कार्रवाई',
    compareBiddersBtn: 'बोलीदाताओं की तुलना करें >',
    comparativeScrutiny: 'तुलनात्मक बोलीदाता जांच',
    rankBidderName: 'रैंक / बोलीदाता का नाम',
    complianceScore: 'अनुपालन स्कोर',
    riskLevel: 'जोखिम स्तर',
    statutoryParity: 'सांविधिक समानता',
    localContent: 'मेक इन इंडिया स्थानीय सामग्री',
    detailAudit: 'विस्तृत ऑडिट',
    lowRisk: 'निम्न (LOW)',
    mediumRisk: 'मध्यम (MEDIUM)',
    highRisk: 'उच्च (HIGH)',
    backToTenders: '< निविदाओं पर वापस जाएं',
    backToComparison: '< तुलना पर वापस जाएं',
    backToDetail: '< विवरण पर वापस जाएं',
    backToScrutiny: '< जांच पर वापस जाएं',
    statutoryVerification: 'सांविधिक सत्यापन',
    tenderVerification: 'निविदा-विशिष्ट सत्यापन',
    inspect: 'निरीक्षण करें',
    explainableRisk: 'व्याख्या योग्य जोखिम और अनुपालन स्कोर',
    trafficLightTier: 'ट्रैफिक लाइट टीयर',
    factor: 'कारक',
    weight: 'आवंटित भार',
    result: 'परिणाम',
    verdict: 'निर्णय',
    auditTrailTitle: 'पूर्ण सत्यापन ऑडिट ट्रेल और आधिकारिक स्वीकृति गेट',
    verificationTimeline: 'सत्यापन समयरेखा',
    auditTrailTable: 'ऑडिट ट्रेल तालिका',
    timestamp: 'समय',
    check: 'जांच',
    source: 'स्रोत',
    evidence: 'प्रमाण',
    performedBy: 'द्वारा निष्पादित',
    finalDecision: 'अंतिम निर्णय — खरीद अधिकारी',
    committeeRemarks: 'आधिकारिक समिति जांच टिप्पणी',
    approveQualify: 'स्वीकृत / योग्य',
    sendClarification: 'स्पष्टीकरण हेतु भेजें',
    rejectDisqualify: 'अस्वीकृत / अयोग्य',
    exportDossier: 'ऑडिट डोजियर निर्यात करें (.json)',
    uploadMissing: 'लापता दस्तावेज़ अपलोड करें',
    runAiExtraction: 'एआई निष्कर्षण और सत्यापन चलाएं',
    signSubmitBid: 'हस्ताक्षर करें और बोली जमा करें',
    updateInfo: 'जानकारी अपडेट करें और पुनः सत्यापित करें',
    enterArn: 'मान्य GSTR-3B ARN दर्ज करें',
    ready: 'तैयार',
    attentionReq: 'ध्यान अपेक्षित',
    portalStatus: 'पोर्टल सत्यापन स्थिति (लाइव सांविधिक एपीआई)',
  },
  bn: {
    govIndia: 'ভারত সরকার',
    ministry: 'বাণিজ্য ও শিল্প মন্ত্রক',
    portalTagline: 'জাতীয় পাবলিক প্রকিউরমেন্ট পোর্টাল',
    skipToMain: 'মূল সামগ্রীতে যান',
    raiseTicket: 'টিকিট তৈরি করুন',
    needHelp: 'সাহায্য দরকার ?',
    fontSize: 'ফন্ট সাইজ',
    darkMode: 'ডার্ক মোড',
    lightMode: 'লাইট মোড',
    gemTitle: 'গভর্নমেন্ট ই মার্কেটপ্লেস',
    gemMotto: 'দক্ষ • স্বচ্ছ • অন্তর্ভুক্তিমূলক',
    searchPlaceholder: 'GeM-এ কিছু খুঁজছেন?',
    products: 'পণ্যসমূহ',
    services: 'সেবাসমূহ',
    content: 'বিষয়বস্তু',
    courses: 'প্রশিক্ষণ কোর্স',
    forwardAuction: 'ফরোয়ার্ড নিলাম',
    bids: 'বিডসমূহ',
    signUp: 'সাইন আপ',
    login: 'লগইন',
    aiEngine: '⚡ এআই সংবিধিবদ্ধ ইঞ্জিন',
    categories: 'বিভাগসমূহ',
    home: 'হোম',
    features: 'সুবিধা ও বৈশিষ্ট্য',
    sellerOnGem: 'GeM-এ বিক্রেতা',
    viewContracts: 'চুক্তি দেখুন',
    cppp: 'সিপিপিপি',
    heroDecade: 'বিশ্বাস ও রূপান্তরের',
    heroDecadeSub: 'দশক',
    heroMotto: 'অসীম সম্ভাবনার দশক',
    heroCelebrate: 'নতুন সুযোগ সৃষ্টির এক সফল দশক',
    heroSub2: 'আসুন, এই ঐতিহাসিক রূপান্তরের অংশীদার হোন',
    askGemmy: 'GeMMy-কে জিজ্ঞাসা করুন',
    askGemmySub: '(এআই চালিত)',
    sellerDesk: 'বিক্রেতা সম্মতি ডেস্ক',
    officerPortal: 'সংগ্রহ কর্মকর্তা পোর্টাল',
    gmv: 'মোট লেনদেন মূল্য',
    ordersProcessed: 'সম্পন্ন অর্ডার',
    registeredSellers: 'নিবন্ধিত বিক্রেতা',
    primaryBuyers: 'যাচাইকৃত ক্রেতা',
    vocalForLocal: '#vocalforlocal',
    gemOutlets: 'GeM আউটলেট স্টোরসমূহ',
    popularProducts: 'জনপ্রিয় পণ্য বিভাগ',
    popularServices: 'জনপ্রিয় পরিষেবা বিভাগ',
    whyChooseGem: 'কেন GeM বেছে নেবেন',
    customersSpeak: 'গ্রাহকদের মতামত',
    exploreMarket: 'বাজার অন্বেষণ করুন',
    viewAllServices: 'সকল পরিষেবা দেখুন',
    footerRuleNotice: 'সংবিধিবদ্ধ সম্মতি এবং GFR নিয়ম 144(xi) যাচাইকরণ গেটওয়ে',
    footerCopyright: '© 2026 গভর্নমেন্ট ই মার্কেটপ্লেস (GeM). স্মার্ট ইন্ডিয়া হ্যাকাথন (SIH26100).',
    activeTenders: 'সক্রিয় দরপত্র',
    compareBidders: 'দরদাতাদের তুলনা',
    deepAudit: 'গভীর অডিট',
    findingsRisk: 'ফলাফল ও ঝুঁকি',
    auditSignOff: 'অডিট ও চূড়ান্ত সিদ্ধান্ত',
    dashboard: 'ড্যাশবোর্ড',
    officerConsole: 'সংগ্রহ কর্মকর্তা যাচাই কনসোল',
    sellerPortal: 'বিক্রেতা সম্মতি পোর্টাল',
    logout: 'লগআউট',
    gemHome: 'GeM হোম',
    close: 'বন্ধ করুন',
    submit: 'জমা দিন',
    cancel: 'বাতিল',
    readiness: 'সম্মতি প্রস্তুতি',
    verified: 'যাচাইকৃত',
    pending: 'মুলতুবি',
    issues: 'সমস্যাসমূহ',
    discrepancies: 'অসঙ্গতি চিহ্নিত',
    activeProcurementTenders: 'সক্রিয় পাবলিক সংগ্রহ দরপত্র',
    activeTendersSub: 'দরপত্র বিডসমূহের লাইভ পর্যবেক্ষণ ও সম্মতি যাচাইকরণ।',
    bidsUnderScrutiny: 'পরীক্ষাধীন বিডসমূহ',
    aiScannedBids: 'এআই স্ক্যানকৃত বিডসমূহ',
    tenderRefNo: 'দরপত্র রেফারেন্স নং',
    description: 'বিবরণ',
    bidders: 'দরদাতা',
    aiScrutinyStatus: 'এআই যাচাই অবস্থা',
    action: 'পদক্ষেপ',
    compareBiddersBtn: 'দরদাতাদের তুলনা করুন >',
    comparativeScrutiny: 'তুলনামূলক দরদাতা যাচাই',
    rankBidderName: 'র‍্যাঙ্ক / দরদাতার নাম',
    complianceScore: 'সম্মতি স্কোর',
    riskLevel: 'ঝুঁকির মাত্রা',
    statutoryParity: 'বিধিবদ্ধ সামঞ্জস্য',
    localContent: 'মেক ইন ইন্ডিয়া স্থানীয় সামগ্রী',
    detailAudit: 'বিস্তারিত অডিট',
    lowRisk: 'নিম্ন (LOW)',
    mediumRisk: 'মাঝারি (MEDIUM)',
    highRisk: 'উচ্চ (HIGH)',
    backToTenders: '< দরপত্রে ফিরে যান',
    backToComparison: '< তুলনায় ফিরে যান',
    backToDetail: '< বিস্তারিত ফিরে যান',
    backToScrutiny: '< যাচাইয়ে ফিরে যান',
    statutoryVerification: 'বিধিবদ্ধ যাচাইকরণ',
    tenderVerification: 'দরপত্র-নির্দিষ্ট যাচাইকরণ',
    inspect: 'পরিদর্শন',
    explainableRisk: 'ব্যাখ্যাযোগ্য ঝুঁকি ও সম্মতি স্কোর',
    trafficLightTier: 'ট্র্যাফিক লাইট স্তর',
    factor: 'উপাদান',
    weight: 'নির্ধারিত ওজন',
    result: 'ফলাফল',
    verdict: 'রায়',
    auditTrailTitle: 'সম্পূর্ণ অডিট ট্রেইল ও অফিসিয়াল অনুমোদন',
    verificationTimeline: 'যাচাইকরণের সময়রেখা',
    auditTrailTable: 'অডিট ট্রেইল টেবিল',
    timestamp: 'সময়',
    check: 'যাচাই',
    source: 'উৎস',
    evidence: 'প্রমাণ',
    performedBy: 'সম্পাদনকারী',
    finalDecision: 'চূড়ান্ত সিদ্ধান্ত — সংগ্রহ কর্মকর্তা',
    committeeRemarks: 'অফিসিয়াল কমিটি যাচাই মন্তব্য',
    approveQualify: 'অনুমোদন / যোগ্য',
    sendClarification: 'স্পষ্টীকরণের জন্য পাঠান',
    rejectDisqualify: 'বাতিল / অযোগ্য',
    exportDossier: 'অডিট ডসিয়ার রপ্তানি করুন (.json)',
    uploadMissing: 'অনুপস্থিত নথি আপলোড করুন',
    runAiExtraction: 'এআই এক্সট্রাকশন ও যাচাই চালান',
    signSubmitBid: 'স্বাক্ষর ও বিড জমা দিন',
    updateInfo: 'তথ্য আপডেট ও পুনঃযাচাই করুন',
    enterArn: 'বৈধ GSTR-3B ARN লিখুন',
    ready: 'প্রস্তুত',
    attentionReq: 'মনোযোগ প্রয়োজন',
    portalStatus: 'পোর্টাল যাচাইকরণ অবস্থা (লাইভ বিধিবদ্ধ এপিআই)',
  },
  te: {
    govIndia: 'భారత ప్రభుత్వం',
    ministry: 'వాణిజ్య మరియు పరిశ్రమల మంత్రిత్వ శాఖ',
    portalTagline: 'జాతీయ పబ్లిక్ ప్రొక్యూర్మెంట్ పోర్టల్',
    skipToMain: 'ప్రధాన కంటెంట్‌కి వెళ్లండి',
    raiseTicket: 'టికెట్ రైజ్ చేయండి',
    needHelp: 'సహాయం కావాలా ?',
    fontSize: 'ఫాంట్ పరిమాణం',
    darkMode: 'డార్క్ మోడ్',
    lightMode: 'లైట్ మోడ్',
    gemTitle: 'గవర్నమెంట్ ఈ మార్కెట్‌ప్లేస్',
    gemMotto: 'సమర్థవంతమైన • పారదర్శక • సమ్మిళిత',
    searchPlaceholder: 'GeM లో ఏదైనా వెతుకుతున్నారా?',
    products: 'ఉత్పత్తులు',
    services: 'సేవలు',
    content: 'కంటెంట్',
    courses: 'శిక్షణా కోర్సులు',
    forwardAuction: 'ఫార్వర్డ్ వేలం',
    bids: 'బిడ్లు',
    signUp: 'సైన్ అప్',
    login: 'లాగిన్',
    aiEngine: '⚡ AI చట్టబద్ధమైన ఇంజిన్',
    categories: 'వర్గాలు',
    home: 'హోమ్',
    features: 'ఫీచర్లు & ప్రయోజనాలు',
    sellerOnGem: 'GeM లో విక్రేత',
    viewContracts: 'ఒప్పందాలను చూడండి',
    cppp: 'CPPP',
    heroDecade: 'విశ్వాసం మరియు మార్పుల',
    heroDecadeSub: 'దశాబ్దం',
    heroMotto: 'అనంతమైన అవకాశాల దశాబ్దం',
    heroCelebrate: 'కొత్త అవకాశాలకు రెక్కలు తొడిగిన దశాబ్దం',
    heroSub2: 'ఈ పరివర్తన యాత్రలో భాగస్వామ్యం అవ్వండి',
    askGemmy: 'GeMMy ని అడగండి',
    askGemmySub: '(AI ఆధారిత)',
    sellerDesk: 'విక్రేత వర్తింపు డెస్క్',
    officerPortal: 'కొనుగోలు అధికారి పోర్టల్',
    gmv: 'మొత్తం వాణిజ్య విలువ',
    ordersProcessed: 'పూర్తయిన ఆర్డర్లు',
    registeredSellers: 'నమోదైన విక్రేతలు',
    primaryBuyers: 'ధృవీకరించబడిన కొనుగోలుదారులు',
    vocalForLocal: '#vocalforlocal',
    gemOutlets: 'GeM అవుట్‌లెట్ స్టోర్‌లు',
    popularProducts: 'ప్రసిద్ధ ఉత్పత్తుల వర్గాలు',
    popularServices: 'ప్రసిద్ధ సేవల వర్గాలు',
    whyChooseGem: 'మీరు GeM ని ఎందుకు ఎంచుకోవాలి',
    customersSpeak: 'కస్టమర్ల అనుభవాలు',
    exploreMarket: 'మార్కెట్‌ను అన్వేషించండి',
    viewAllServices: 'అన్ని సేవలను చూడండి',
    footerRuleNotice: 'చట్టబద్ధమైన వర్తింపు మరియు GFR నిబంధన 144(xi) ధృవీకరణ గేట్‌వే',
    footerCopyright: '© 2026 గవర్నమెంట్ ఈ మార్కెట్‌ప్లేస్ (GeM). స్మార్ట్ ఇండియా హ్యాకథాన్ (SIH26100).',
    activeTenders: 'క్రియాశీల టెండర్లు',
    compareBidders: 'బిడ్డర్ల పోలిక',
    deepAudit: 'లోతైన ఆడిట్',
    findingsRisk: 'ఫలితాలు & ప్రమాదం',
    auditSignOff: 'ఆడిట్ & తుది నిర్ణయం',
    dashboard: 'డాష్‌బోర్డ్',
    officerConsole: 'కొనుగోలు అధికారి పరిశీలన కన్సోల్',
    sellerPortal: 'విక్రేత వర్తింపు పోర్టల్',
    logout: 'లాగౌట్',
    gemHome: 'GeM హోమ్',
    close: 'మూసివేయి',
    submit: 'సమర్పించు',
    cancel: 'రద్దు చేయి',
    readiness: 'వర్తింపు సంసిద్ధత',
    verified: 'ధృవీకరించబడింది',
    pending: 'పెండింగ్‌లో ఉంది',
    issues: 'సమస్యలు',
    discrepancies: 'వ్యత్యాసాలు గుర్తించబడ్డాయి',
    activeProcurementTenders: 'క్రియాశీల కొనుగోలు టెండర్లు',
    activeTendersSub: 'టెండర్ బిడ్ల ప్రత్యక్ష పర్యవేక్షణ మరియు స్వయంచాలక విశ్లేషణ.',
    bidsUnderScrutiny: 'పరిశీలనలో ఉన్న బిడ్లు',
    aiScannedBids: 'AI స్కాన్ చేసిన బిడ్లు',
    tenderRefNo: 'టెండర్ రిఫరెన్స్ సంఖ్య',
    description: 'వివరణ',
    bidders: 'బిడ్డర్లు',
    aiScrutinyStatus: 'AI పరిశీలన స్థితి',
    action: 'చర్య',
    compareBiddersBtn: 'బిడ్డర్లను పోల్చండి >',
    comparativeScrutiny: 'తులనాత్మక బిడ్డర్ పరిశీలన',
    rankBidderName: 'ర్యాంక్ / బిడ్డర్ పేరు',
    complianceScore: 'వర్తింపు స్కోర్',
    riskLevel: 'ప్రమాద స్థాయి',
    statutoryParity: 'చట్టబద్ధమైన సమానత్వం',
    localContent: 'మేక్ ఇన్ ఇండియా స్థానిక కంటెంట్',
    detailAudit: 'సమగ్ర ఆడిట్',
    lowRisk: 'తక్కువ (LOW)',
    mediumRisk: 'మధ్యస్థం (MEDIUM)',
    highRisk: 'ఎక్కువ (HIGH)',
    backToTenders: '< టెండర్లకు తిరిగి వెళ్ళు',
    backToComparison: '< పోలికకు తిరిగి వెళ్ళు',
    backToDetail: '< వివరాలకు తిరిగి వెళ్ళు',
    backToScrutiny: '< పరిశీలనకు తిరిగి వెళ్ళు',
    statutoryVerification: 'చట్టబద్ధమైన ధృవీకరణ',
    tenderVerification: 'టెండర్ నిర్దిష్ట ధృవీకరణ',
    inspect: 'తనిఖీ చేయండి',
    explainableRisk: 'వివరించదగిన రిస్క్ & వర్తింపు స్కోర్',
    trafficLightTier: 'ట్రాఫిక్ లైట్ శ్రేణి',
    factor: 'అంశం',
    weight: 'కేటాయించిన బరువు',
    result: 'ఫలితం',
    verdict: 'తీర్పు',
    auditTrailTitle: 'పూర్తి ఆడిట్ ట్రయిల్ & అధికారిక ఆమోదం',
    verificationTimeline: 'ధృవీకరణ కాలక్రమం',
    auditTrailTable: 'ఆడిట్ ట్రయిల్ పట్టిక',
    timestamp: 'సమయం',
    check: 'తనిఖీ',
    source: 'మూలం',
    evidence: 'సాక్ష్యం',
    performedBy: 'నిర్వహించిన వారు',
    finalDecision: 'తుది నిర్ణయం — కొనుగోలు అధికారి',
    committeeRemarks: 'కమిటీ పరిశీలన వ్యాఖ్యలు',
    approveQualify: 'ఆమోదించు / అర్హత పొందు',
    sendClarification: 'స్పష్టత కోసం పంపండి',
    rejectDisqualify: 'తిరస్కరించు / అనర్హత',
    exportDossier: 'ఆడిట్ పత్రాన్ని ఎగుమతి చేయండి (.json)',
    uploadMissing: 'తప్పిపోయిన పత్రాన్ని అప్‌లోడ్ చేయండి',
    runAiExtraction: 'AI సంగ్రహణ & ధృవీకరణను అమలు చేయండి',
    signSubmitBid: 'సంతకం చేసి బిడ్ సమర్పించండి',
    updateInfo: 'సమాచారాన్ని నవీకరించండి & పునఃధృవీకరించండి',
    enterArn: 'సరైన GSTR-3B ARN నమోదు చేయండి',
    ready: 'సిద్ధంగా ఉంది',
    attentionReq: 'శ్రద్ధ అవసరం',
    portalStatus: 'పోర్టల్ ధృవీకరణ స్థితి (ప్రత్యక్ష చట్టబద్ధమైన APIలు)',
  },
  mr: {
    govIndia: 'भारत सरकार',
    ministry: 'वाणिज्य आणि उद्योग मंत्रालय',
    portalTagline: 'राष्ट्रीय सार्वजनिक खरेदी पोर्टल',
    skipToMain: 'मुख्य मजकुरावर जा',
    raiseTicket: 'तक्रार नोंदवा',
    needHelp: 'मदत हवी आहे ?',
    fontSize: 'फॉन्ट आकार',
    darkMode: 'डार्क मोड',
    lightMode: 'लाइट मोड',
    gemTitle: 'गव्हर्नमेंट ई मार्केटप्लेस',
    gemMotto: 'कार्यक्षम • पारदर्शक • सर्वसमावेशक',
    searchPlaceholder: 'GeM वर काही शोधत आहात?',
    products: 'उत्पादने',
    services: 'सेवा',
    content: 'सामग्री',
    courses: 'प्रशिक्षण अभ्यासक्रम',
    forwardAuction: 'फॉरवर्ड लिलाव',
    bids: 'निविदा',
    signUp: 'साइन अप',
    login: 'लॉग इन',
    aiEngine: '⚡ एआय वैधानिक इंजिन',
    categories: 'श्रेण्या',
    home: 'मुख्यपृष्ठ',
    features: 'वैशिष्ट्ये व फायदे',
    sellerOnGem: 'GeM वरील विक्रेता',
    viewContracts: 'करार पहा',
    cppp: 'सीपीपीपी',
    heroDecade: 'विश्वास आणि परिवर्तनाचे',
    heroDecadeSub: 'दशक',
    heroMotto: 'अमर्याद संधींचे दशक',
    heroCelebrate: 'संधींना नवी भरारी देणाऱ्या दशकाचा उत्सव',
    heroSub2: 'या परिवर्तनकारी प्रवासाचा भाग व्हा',
    askGemmy: 'GeMMy ला विचारा',
    askGemmySub: '(एआय समर्थित)',
    sellerDesk: 'विक्रेता अनुपालन डेस्क',
    officerPortal: 'खरेदी अधिकारी पोर्टल',
    gmv: 'एकूण व्यापार मूल्य',
    ordersProcessed: 'प्रक्रिया केलेल्या ऑर्डर्स',
    registeredSellers: 'नोंदणीकृत विक्रेते',
    primaryBuyers: 'सत्यापित खरेदीदार',
    vocalForLocal: '#vocalforlocal',
    gemOutlets: 'GeM आउटलेट स्टोअर्स',
    popularProducts: 'लोकप्रिय उत्पादन श्रेण्या',
    popularServices: 'लोकप्रिय सेवा श्रेण्या',
    whyChooseGem: 'GeM का निवडावे',
    customersSpeak: 'ग्राहकांचे अभिप्राय',
    exploreMarket: 'बाजारपेठ एक्सप्लोर करा',
    viewAllServices: 'सर्व सेवा पहा',
    footerRuleNotice: 'वैधानिक अनुपालन आणि GFR नियम 144(xi) पडताळणी गेटवे',
    footerCopyright: '© 2026 गव्हर्नमेंट ई मार्केटप्लेस (GeM). स्मार्ट इंडिया हॅकाथॉन (SIH26100).',
    activeTenders: 'सक्रिय निविदा',
    compareBidders: 'बोलीदारांची तुलना',
    deepAudit: 'सखोल ऑडिट',
    findingsRisk: 'निष्कर्ष आणि जोखीम',
    auditSignOff: 'ऑडिट आणि अंतिम मंजुरी',
    dashboard: 'डॅशबोर्ड',
    officerConsole: 'खरेदी अधिकारी छाननी कन्सोल',
    sellerPortal: 'विक्रेता अनुपालन पोर्टल',
    logout: 'लॉगआउट',
    gemHome: 'GeM मुख्यपृष्ठ',
    close: 'बंद करा',
    submit: 'प्रस्तुत करा',
    cancel: 'रद्द करा',
    readiness: 'अनुपालन सज्जता',
    verified: 'पडताळणी पूर्ण',
    pending: 'प्रलंबित',
    issues: 'समस्या',
    discrepancies: 'विसंगती आढळल्या',
    activeProcurementTenders: 'सक्रिय खरेदी निविदा',
    activeTendersSub: 'निविदा बोलींचे थेट निरीक्षण आणि स्वयंचलित अनुपालन विश्लेषण.',
    bidsUnderScrutiny: 'छाननी अंतर्गत बोली',
    aiScannedBids: 'एआय स्कॅन केलेल्या बोली',
    tenderRefNo: 'निविदा संदर्भ क्र.',
    description: 'तपशील',
    bidders: 'बोलीदार',
    aiScrutinyStatus: 'एआय छाननी स्थिती',
    action: 'कृती',
    compareBiddersBtn: 'बोलीदारांची तुलना करा >',
    comparativeScrutiny: 'तुलनात्मक बोलीदार छाननी',
    rankBidderName: 'रँक / बोलीदाराचे नाव',
    complianceScore: 'अनुपालन गुण',
    riskLevel: 'जोखीम पातळी',
    statutoryParity: 'वैधानिक सुसंगतता',
    localContent: 'मेक इन इंडिया स्थानिक सामग्री',
    detailAudit: 'सविस्तर ऑडिट',
    lowRisk: 'कमी (LOW)',
    mediumRisk: 'मध्यम (MEDIUM)',
    highRisk: 'जास्त (HIGH)',
    backToTenders: '< निविदांवर परत जा',
    backToComparison: '< तुलनेवर परत जा',
    backToDetail: '< तपशीलावर परत जा',
    backToScrutiny: '< छाननीवर परत जा',
    statutoryVerification: 'वैधानिक पडताळणी',
    tenderVerification: 'निविदा-विशिष्ट पडताळणी',
    inspect: 'तपासा',
    explainableRisk: 'स्पष्टीकरणात्मक जोखीम आणि अनुपालन गुण',
    trafficLightTier: 'ट्रॅफिक लाइट स्तर',
    factor: 'घटक',
    weight: 'नियुक्त भार',
    result: 'निकाल',
    verdict: 'निर्णय',
    auditTrailTitle: 'पूर्ण ऑडिट ट्रेल आणि अधिकृत मंजुरी गेट',
    verificationTimeline: 'पडताळणी टाइमलाइन',
    auditTrailTable: 'ऑडिट ट्रेल तक्ता',
    timestamp: 'वेळ',
    check: 'तपासणी',
    source: 'स्रोत',
    evidence: 'पुरावा',
    performedBy: 'द्वारे संपन्न',
    finalDecision: 'अंतिम निर्णय — खरेदी अधिकारी',
    committeeRemarks: 'अधिकृत समिती छाननी शेरे',
    approveQualify: 'मंजूर / पात्र',
    sendClarification: 'स्पष्टीकरणासाठी पाठवा',
    rejectDisqualify: 'नाकारले / अपात्र',
    exportDossier: 'ऑडिट डॉसियर निर्यात करा (.json)',
    uploadMissing: 'गहाळ कागदपत्र अपलोड करा',
    runAiExtraction: 'एआय निष्कर्ष आणि पडताळणी चालवा',
    signSubmitBid: 'स्वाक्षरी करून बोली जमा करा',
    updateInfo: 'माहिती अद्यतनित करा आणि पुन्हा तपासा',
    enterArn: 'वैध GSTR-3B ARN प्रविष्ट करा',
    ready: 'सज्ज',
    attentionReq: 'लक्ष देणे आवश्यक',
    portalStatus: 'पोर्टल पडताळणी स्थिती (थेट वैधानिक एपीआय)',
  },
  ta: {
    govIndia: 'இந்திய அரசு',
    ministry: 'வர்த்தக மற்றும் தொழில்துறை அமைச்சகம்',
    portalTagline: 'தேசிய பொது கொள்முதல் தளம்',
    skipToMain: 'முதன்மை உள்ளடக்கத்திற்கு செல்க',
    raiseTicket: 'கோரிக்கை பதிவு செய்க',
    needHelp: 'உதவி தேவையா ?',
    fontSize: 'எழுத்துரு அளவு',
    darkMode: 'டார்க் மோட்',
    lightMode: 'லைட் மோட்',
    gemTitle: 'அரசு மின் சந்தை',
    gemMotto: 'திறமையான • வெளிப்படையான • அனைவரையும் உள்ளடக்கிய',
    searchPlaceholder: 'GeM இல் தேடுகிறீர்களா?',
    products: 'பொருட்கள்',
    services: 'சேவைகள்',
    content: 'உள்ளடக்கம்',
    courses: 'பயிற்சி வகுப்புகள்',
    forwardAuction: 'முன்னோக்கு ஏலம்',
    bids: 'டெண்டர்கள்',
    signUp: 'பதிவு செய்க',
    login: 'உள்நுழைக',
    aiEngine: '⚡ AI சட்டரீதியான இயந்திரம்',
    categories: 'பிரிவுகள்',
    home: 'முகப்பு',
    features: 'அம்சங்கள் & நன்மைகள்',
    sellerOnGem: 'GeM-ல் விற்பனையாளர்',
    viewContracts: 'ஒப்பந்தங்களைக் காண்க',
    cppp: 'CPPP',
    heroDecade: 'நம்பிக்கை மற்றும் மாற்றத்தின்',
    heroDecadeSub: 'பத்தாண்டு',
    heroMotto: 'வரம்பற்ற வாய்ப்புகளின் பத்தாண்டு',
    heroCelebrate: 'புதிய வாய்ப்புகளுக்கு வழிவகுத்த பத்தாண்டுகளின் கொண்டாட்டம்',
    heroSub2: 'இந்த வரலாற்று மாற்றத்தில் இணையுங்கள்',
    askGemmy: 'GeMMy-யிடம் கேளுங்கள்',
    askGemmySub: '(AI இயங்குதளம்)',
    sellerDesk: 'விற்பனையாளர் இணக்க மேசை',
    officerPortal: 'கொள்முதல் அதிகாரி தளம்',
    gmv: 'மொத்த வர்த்தக மதிப்பு',
    ordersProcessed: 'நிறைவேற்றப்பட்ட ஆர்டர்கள்',
    registeredSellers: 'பதிவுசெய்த விற்பனையாளர்கள்',
    primaryBuyers: 'சரிபார்க்கப்பட்ட வாங்குபவர்கள்',
    vocalForLocal: '#vocalforlocal',
    gemOutlets: 'GeM விற்பனை நிலையங்கள்',
    popularProducts: 'பிரபலமான பொருட்கள்',
    popularServices: 'பிரபலமான சேவைகள்',
    whyChooseGem: 'GeM-ஐ ஏன் தேர்வு செய்ய வேண்டும்',
    customersSpeak: 'வாடிக்கையாளர் கருத்துக்கள்',
    exploreMarket: 'சந்தையை ஆராய்க',
    viewAllServices: 'அனைத்து சேவைகளையும் காண்க',
    footerRuleNotice: 'சட்டரீதியான இணக்கம் மற்றும் GFR விதி 144(xi) சரிபார்ப்பு போர்ட்டல்',
    footerCopyright: '© 2026 அரசு மின் சந்தை (GeM). ஸ்மார்ட் இந்தியா ஹேக்கத்தான் (SIH26100).',
    activeTenders: 'செயலில் உள்ள டெண்டர்கள்',
    compareBidders: 'ஏலதாரர்களை ஒப்பிடுக',
    deepAudit: 'ஆழ்ந்த தணிக்கை',
    findingsRisk: 'கண்டுபிடிப்புகள் & ஆபத்து',
    auditSignOff: 'தணிக்கை & இறுதி முடிவு',
    dashboard: 'டாஷ்போர்டு',
    officerConsole: 'கொள்முதல் அதிகாரி சரிபார்ப்பு கன்சோல்',
    sellerPortal: 'விற்பனையாளர் இணக்க தளம்',
    logout: 'வெளியேறு',
    gemHome: 'GeM முகப்பு',
    close: 'மூடுக',
    submit: 'சமர்ப்பிக்கவும்',
    cancel: 'ரத்து செய்',
    readiness: 'இணக்கத் தயார்நிலை',
    verified: 'சரிபார்க்கப்பட்டது',
    pending: 'நிலுவையில் உள்ளது',
    issues: 'சிக்கல்கள்',
    discrepancies: 'முரண்பாடுகள் கண்டறியப்பட்டன',
    activeProcurementTenders: 'செயலில் உள்ள பொது கொள்முதல் டெண்டர்கள்',
    activeTendersSub: 'டெண்டர் ஏலங்களின் நேரடி கண்காணிப்பு மற்றும் தானியங்கி சரிபார்ப்பு.',
    bidsUnderScrutiny: 'பரிசீலனையில் உள்ள ஏலங்கள்',
    aiScannedBids: 'AI ஸ்கேன் செய்யப்பட்ட ஏலங்கள்',
    tenderRefNo: 'டெண்டர் குறிப்பு எண்',
    description: 'விளக்கம்',
    bidders: 'ஏலதாரர்கள்',
    aiScrutinyStatus: 'AI பரிசீலனை நிலை',
    action: 'செயல்',
    compareBiddersBtn: 'ஏலதாரர்களை ஒப்பிடுக >',
    comparativeScrutiny: 'ஒப்பீட்டு ஏலதாரர் பரிசீலனை',
    rankBidderName: 'தரம் / ஏலதாரர் பெயர்',
    complianceScore: 'இணக்க மதிப்பெண்',
    riskLevel: 'ஆபத்து நிலை',
    statutoryParity: 'சட்டரீதியான இணக்கம்',
    localContent: 'மேக் இன் இந்தியா உள்ளூர் உள்ளடக்கம்',
    detailAudit: 'விரிவான தணிக்கை',
    lowRisk: 'குறைந்த (LOW)',
    mediumRisk: 'நடுத்தர (MEDIUM)',
    highRisk: 'அதிக (HIGH)',
    backToTenders: '< டெண்டர்களுக்குத் திரும்பு',
    backToComparison: '< ஒப்பீட்டுக்குத் திரும்பு',
    backToDetail: '< விவரங்களுக்குத் திரும்பு',
    backToScrutiny: '< பரிசீலனைக்குத் திரும்பு',
    statutoryVerification: 'சட்டப்பூர்வ சரிபார்ப்பு',
    tenderVerification: 'டெண்டர் சார்ந்த சரிபார்ப்பு',
    inspect: 'ஆய்வு செய்',
    explainableRisk: 'விளக்கக்கூடிய ஆபத்து மற்றும் இணக்க மதிப்பெண்',
    trafficLightTier: 'ட்ராஃபிக் லைட் அடுக்கு',
    factor: 'காரணி',
    weight: 'ஒதுக்கப்பட்ட எடை',
    result: 'முடிவு',
    verdict: 'தீர்ப்பு',
    auditTrailTitle: 'முழுமையான தணிக்கை பாதை & அதிகாரப்பூர்வ ஒப்புதல்',
    verificationTimeline: 'சரிபார்ப்பு காலவரிசை',
    auditTrailTable: 'தணிக்கை பதிவு அட்டவணை',
    timestamp: 'நேரம்',
    check: 'சோதனை',
    source: 'மூலம்',
    evidence: 'சான்று',
    performedBy: 'செய்தவர்',
    finalDecision: 'இறுதி முடிவு — கொள்முதல் அதிகாரி',
    committeeRemarks: 'அதிகாரப்பூர்வ குழு பரிசீலனை குறிப்புகள்',
    approveQualify: 'ஒப்புதல் / தகுதி பெற்றது',
    sendClarification: 'விளக்கத்திற்கு அனுப்புக',
    rejectDisqualify: 'நிராகரி / தகுதியற்றது',
    exportDossier: 'தணிக்கை ஆவணத்தை ஏற்றுமதி செய்க (.json)',
    uploadMissing: 'விடுபட்ட ஆவணத்தை பதிவேற்றவும்',
    runAiExtraction: 'AI பிரித்தெடுத்தல் மற்றும் சரிபார்ப்பை இயக்கு',
    signSubmitBid: 'கையொப்பமிட்டு ஏலத்தை சமர்ப்பிக்கவும்',
    updateInfo: 'தகவலைப் புதுப்பித்து மீண்டும் சரிபார்க்கவும்',
    enterArn: 'சரியான GSTR-3B ARN ஐ உள்ளிடவும்',
    ready: 'தயார்',
    attentionReq: 'கவனம் தேவை',
    portalStatus: 'போர்டல் சரிபார்ப்பு நிலை (நேரலை சட்டரீதியான APIகள்)',
  },
  gu: {
    govIndia: 'ભારત સરકાર',
    ministry: 'વાણિજ્ય અને ઉદ્યોગ મંત્રાલય',
    portalTagline: 'રાષ્ટ્રીય સાર્વજનિક ખરીદી પોર્ટલ',
    skipToMain: 'મુખ્ય વિષયવસ્તુ પર જાઓ',
    raiseTicket: 'ફરિયાદ નોંધાવો',
    needHelp: 'મદદ જોઈએ છે ?',
    fontSize: 'ફોન્ટ કદ',
    darkMode: 'ડાર્ક મોડ',
    lightMode: 'લાઇટ મોડ',
    gemTitle: 'ગવર્નમેન્ટ ઈ માર્કેટપ્લેસ',
    gemMotto: 'કાર્યક્ષમ • પારદર્શક • સમાવેશી',
    searchPlaceholder: 'GeM પર કંઈક શોધી રહ્યાં છો?',
    products: 'ઉત્પાદનો',
    services: 'સેવાઓ',
    content: 'સામગ્રી',
    courses: 'તાલીમ અભ્યાસક્રમો',
    forwardAuction: 'ફોરવર્ડ હરાજી',
    bids: 'બિડ્સ',
    signUp: 'સાઇન અપ',
    login: 'લૉગિન',
    aiEngine: '⚡ AI વૈધાનિક એન્જિન',
    categories: 'શ્રેણીઓ',
    home: 'હોમ',
    features: 'સુવિધાઓ અને લાભો',
    sellerOnGem: 'GeM પર વિક્રેતા',
    viewContracts: 'કરારો જુઓ',
    cppp: 'CPPP',
    heroDecade: 'વિશ્વાસ અને પરિવર્તનનો',
    heroDecadeSub: 'દાયકો',
    heroMotto: 'અસીમ સંભાવનાઓનો દાયકો',
    heroCelebrate: 'તકોને નવી ઊંચાઈ આપનાર દાયકાની ઉજવણી',
    heroSub2: 'આ પરિવર્તનશીલ યાત્રાનો હિસ્સો બનો',
    askGemmy: 'GeMMy ને પૂછો',
    askGemmySub: '(AI સંચાલિત)',
    sellerDesk: 'વિક્રેતા અનુપાલન ડેસ્ક',
    officerPortal: 'ખરીદ અધિકારી પોર્ટલ',
    gmv: 'કુલ વ્યાપારી મૂલ્ય',
    ordersProcessed: 'સફળ ઓર્ડર્સ',
    registeredSellers: 'નોંધાયેલા વિક્રેતાઓ',
    primaryBuyers: 'ચકાસાયેલ ખરીદદારો',
    vocalForLocal: '#vocalforlocal',
    gemOutlets: 'GeM આઉટલેટ સ્ટોર્સ',
    popularProducts: 'લોકપ્રિય ઉત્પાદન શ્રેણીઓ',
    popularServices: 'લોકપ્રિય સેવા શ્રેણીઓ',
    whyChooseGem: 'GeM શા માટે પસંદ કરવું',
    customersSpeak: 'ગ્રાહકોના મંતવ્યો',
    exploreMarket: 'બજારનું અન્વેષણ કરો',
    viewAllServices: 'બધી સેવાઓ જુઓ',
    footerRuleNotice: 'વૈધાનિક અનુપાલન અને GFR નિયમ 144(xi) ચકાસણી ગેટવે',
    footerCopyright: '© 2026 ગવર્નમેન્ટ ઈ માર્કેટપ્લેસ (GeM). સ્માર્ટ ઈન્ડિયા હેકાથોન (SIH26100).',
    activeTenders: 'સક્રિય ટેન્ડરો',
    compareBidders: 'બોલીદાતાઓની સરખામણી',
    deepAudit: 'ઊંડાણપૂર્વક ઓડિટ',
    findingsRisk: 'તારણો અને જોખમ',
    auditSignOff: 'ઓડિટ અને અંતિમ મંજૂરી',
    dashboard: 'ડેશબોર્ડ',
    officerConsole: 'ખરીદ અધિકારી ચકાસણી કન્સોલ',
    sellerPortal: 'વિક્રેતા અનુપાલન પોર્ટલ',
    logout: 'લૉગઆઉટ',
    gemHome: 'GeM હોમ',
    close: 'બંધ કરો',
    submit: 'સબમિટ કરો',
    cancel: 'રદ કરો',
    readiness: 'અનુપાલન સજ્જતા',
    verified: 'ચકાસાયેલ',
    pending: 'બાકી',
    issues: 'સમસ્યાઓ',
    discrepancies: 'વિસંગતતાઓ ચિહ્નિત',
    activeProcurementTenders: 'સક્રિય ખરીદી ટેન્ડરો',
    activeTendersSub: 'ટેન્ડર બિડ્સનું લાઇવ મોનિટરિંગ અને સ્વચાલિત અનુપાલન વિશ્લેષણ.',
    bidsUnderScrutiny: 'ચકાસણી હેઠળની બિડ્સ',
    aiScannedBids: 'AI સ્કેન કરેલ બિડ્સ',
    tenderRefNo: 'ટેન્ડર સંદર્ભ નં.',
    description: 'વિગત',
    bidders: 'બોલીદાતાઓ',
    aiScrutinyStatus: 'AI ચકાસણી સ્થિતિ',
    action: 'ક્રિયા',
    compareBiddersBtn: 'બોલીદાતાઓની સરખામણી કરો >',
    comparativeScrutiny: 'તુલનાત્મક બોલીદાતા ચકાસણી',
    rankBidderName: 'ક્રમ / બોલીદાતાનું નામ',
    complianceScore: 'અનુપાલન સ્કોર',
    riskLevel: 'જોખમ સ્તર',
    statutoryParity: 'વૈધાનિક સુસંગતતા',
    localContent: 'મેક ઇન ઇન્ડિયા સ્થાનિક સામગ્રી',
    detailAudit: 'વિગતવાર ઓડિટ',
    lowRisk: 'ઓછું (LOW)',
    mediumRisk: 'મધ્યમ (MEDIUM)',
    highRisk: 'વધારે (HIGH)',
    backToTenders: '< ટેન્ડરો પર પાછા જાઓ',
    backToComparison: '< સરખામણી પર પાછા જાઓ',
    backToDetail: '< વિગત પર પાછા જાઓ',
    backToScrutiny: '< ચકાસણી પર પાછા જાઓ',
    statutoryVerification: 'વૈધાનિક ચકાસણી',
    tenderVerification: 'ટેન્ડર-વિશિષ્ટ ચકાસણી',
    inspect: 'તપાસ કરો',
    explainableRisk: 'સ્પષ્ટ કરી શકાય તેવું જોખમ અને અનુપાલન સ્કોર',
    trafficLightTier: 'ટ્રાફિક લાઇટ સ્તર',
    factor: 'પરિબળ',
    weight: 'સોંપેલ ભાર',
    result: 'પરિણામ',
    verdict: 'ચુકાદો',
    auditTrailTitle: 'સંપૂર્ણ ઓડિટ ટ્રેઇલ અને સત્તાવાર મંજૂરી ગેટ',
    verificationTimeline: 'ચકાસણી સમયરેખા',
    auditTrailTable: 'ઓડિટ ટ્રેઇલ ટેબલ',
    timestamp: 'સમય',
    check: 'તપાસ',
    source: 'સ્ત્રોત',
    evidence: 'પુરાવો',
    performedBy: 'દ્વારા સંપન્ન',
    finalDecision: 'અંતિમ નિર્ણય — ખરીદ અધિકારી',
    committeeRemarks: 'સત્તાવાર સમિતિ ચકાસણી નોંધ',
    approveQualify: 'મંજૂર / લાયક',
    sendClarification: 'સ્પષ્ટતા માટે મોકલો',
    rejectDisqualify: 'અસ્વીકાર / અયોગ્ય',
    exportDossier: 'ઓડિટ ડોઝિયર નિકાસ કરો (.json)',
    uploadMissing: 'ગુમ થયેલ દસ્તાવેજ અપલોડ કરો',
    runAiExtraction: 'AI એક્સટ્રેક્શન અને ચકાસણી ચલાવો',
    signSubmitBid: 'સહી કરો અને બિડ સબમિટ કરો',
    updateInfo: 'માહિતી અપડેટ કરો અને ફરી ચકાસો',
    enterArn: 'માન્ય GSTR-3B ARN દાખલ કરો',
    ready: 'તૈયાર',
    attentionReq: 'ધ્યાન જરૂરી',
    portalStatus: 'પોર્ટલ ચકાસણી સ્થિતિ (લાઇવ વૈધાનિક API)',
  },
  kn: {
    govIndia: 'ಭಾರತ ಸರ್ಕಾರ',
    ministry: 'ವಾಣಿಜ್ಯ ಮತ್ತು ಕೈಗಾರಿಕಾ ಸಚಿವಾಲಯ',
    portalTagline: 'ರಾಷ್ಟ್ರೀಯ ಸಾರ್ವಜನಿಕ ಸಂಗ್ರಹಣೆ ಪೋರ್ಟಲ್',
    skipToMain: 'ಮುಖ್ಯ ವಿಷಯಕ್ಕೆ ಹೋಗಿ',
    raiseTicket: 'ದೂರು ದಾಖಲಿಸಿ',
    needHelp: 'ಸಹಾಯ ಬೇಕೇ ?',
    fontSize: 'ಫಾಂಟ್ ಗಾತ್ರ',
    darkMode: 'ಡಾರ್ಕ್ ಮೋಡ್',
    lightMode: 'ಲೈಟ್ ಮೋಡ್',
    gemTitle: 'ಸರ್ಕಾರಿ ಇ ಮಾರುಕಟ್ಟೆ',
    gemMotto: 'ದಕ್ಷ • ಪಾರದರ್ಶಕ • ಅಂತರ್ಗತ',
    searchPlaceholder: 'GeM ನಲ್ಲಿ ಏನನ್ನಾದರೂ ಹುಡುಕುತ್ತಿದ್ದೀರಾ?',
    products: 'ಉತ್ಪನ್ನಗಳು',
    services: 'ಸೇವೆಗಳು',
    content: 'ವಿಷಯ',
    courses: 'ತರಬೇತಿ ಕೋರ್ಸ್‌ಗಳು',
    forwardAuction: 'ಮುಂದಿನ ಹರಾಜು',
    bids: 'ಬಿಡ್‌ಗಳು',
    signUp: 'ಸೈನ್ ಅಪ್',
    login: 'ಲಾಗಿನ್',
    aiEngine: '⚡ AI ಶಾಸನಬದ್ಧ ಎಂಜಿನ್',
    categories: 'ವರ್ಗಗಳು',
    home: 'ಮುಖಪುಟ',
    features: 'ವೈಶಿಷ್ಟ್ಯಗಳು & ಪ್ರಯೋಜನಗಳು',
    sellerOnGem: 'GeM ನಲ್ಲಿ ಮಾರಾಟಗಾರರು',
    viewContracts: 'ಒಪ್ಪಂದಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    cppp: 'CPPP',
    heroDecade: 'ನಂಬಿಕೆ ಮತ್ತು ರೂಪಾಂತರದ',
    heroDecadeSub: 'ದಶಕ',
    heroMotto: 'ಅಪಾರ ಸಾಧ್ಯತೆಗಳ ದಶಕ',
    heroCelebrate: 'ಹೊಸ ಅವಕಾಶಗಳಿಗೆ ರೆಕ್ಕೆ ನೀಡಿದ ದಶಕದ ಆಚರಣೆ',
    heroSub2: 'ಈ ರೂಪಾಂತರದ ಪಯಣದಲ್ಲಿ ಪಾಲ್ಗೊಳ್ಳಿ',
    askGemmy: 'GeMMy ಅನ್ನು ಕೇಳಿ',
    askGemmySub: '(AI ಆಧಾರಿತ)',
    sellerDesk: 'ಮಾರಾಟಗಾರರ ಅನುಸರಣೆ ಡೆಸ್ಕ್',
    officerPortal: 'ಖರೀದಿ ಅಧಿಕಾರಿ ಪೋರ್ಟಲ್',
    gmv: 'ಒಟ್ಟು ವ್ಯಾಪಾರ ಮೌಲ್ಯ',
    ordersProcessed: 'ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಿದ ಆದೇಶಗಳು',
    registeredSellers: 'ನೋಂದಾಯಿತ ಮಾರಾಟಗಾರರು',
    primaryBuyers: 'ಪರಿಶೀಲಿಸಿದ ಖರೀದಿದಾರರು',
    vocalForLocal: '#vocalforlocal',
    gemOutlets: 'GeM ಔಟ್‌ಲೆಟ್ ಮಳಿಗೆಗಳು',
    popularProducts: 'ಜನಪ್ರಿಯ ಉತ್ಪನ್ನ ವಿಭಾಗಗಳು',
    popularServices: 'ಜನಪ್ರಿಯ ಸೇವಾ ವಿಭಾಗಗಳು',
    whyChooseGem: 'ನೀವು GeM ಅನ್ನು ಏಕೆ ಆರಿಸಬೇಕು',
    customersSpeak: 'ಗ್ರಾಹಕರ ಅನುಭವಗಳು',
    exploreMarket: 'ಮಾರುಕಟ್ಟೆಯನ್ನು ಅನ್ವೇಷಿಸಿ',
    viewAllServices: 'ಎಲ್ಲಾ ಸೇವೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    footerRuleNotice: 'ಶಾಸನಬದ್ಧ ಅನುಸರಣೆ ಮತ್ತು GFR ನಿಯಮ 144(xi) ಪರಿಶೀಲನಾ ಗೇಟ್‌ವೇ',
    footerCopyright: '© 2026 ಸರ್ಕಾರಿ ಇ ಮಾರುಕಟ್ಟೆ (GeM). ಸ್ಮಾರ್ಟ್ ಇಂಡಿಯಾ ಹ್ಯಾಕಥಾನ್ (SIH26100).',
    activeTenders: 'ಸಕ್ರಿಯ ಟೆಂಡರ್‌ಗಳು',
    compareBidders: 'ಬಿಡ್ಡುದಾರರ ಹೋಲಿಕೆ',
    deepAudit: 'ಆಳವಾದ ಆಡಿಟ್',
    findingsRisk: 'ಫಲಿತಾಂಶಗಳು & ಅಪಾಯ',
    auditSignOff: 'ಆಡಿಟ್ & ಅಂತಿಮ ತೀರ್ಮಾನ',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    officerConsole: 'ಖರೀದಿ ಅಧಿಕಾರಿ ಪರಿಶೀಲನಾ ಕನ್ಸೋಲ್',
    sellerPortal: 'ಮಾರಾಟಗಾರರ ಅನುಸರಣೆ ಪೋರ್ಟಲ್',
    logout: 'ಲಾಗ್‌ಔಟ್',
    gemHome: 'GeM ಮುಖಪುಟ',
    close: 'ಮುಚ್ಚಿ',
    submit: 'ಸಲ್ಲಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    readiness: 'ಅನುಸರಣೆ ಸಿದ್ಧತೆ',
    verified: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    pending: 'ಬಾಕಿ ಉಳಿದಿದೆ',
    issues: 'ಸಮಸ್ಯೆಗಳು',
    discrepancies: 'ವ್ಯತ್ಯಾಸಗಳನ್ನು ಗುರುತಿಸಲಾಗಿದೆ',
    activeProcurementTenders: 'ಸಕ್ರಿಯ ಸಾರ್ವಜನಿಕ ಸಂಗ್ರಹಣೆ ಟೆಂಡರ್‌ಗಳು',
    activeTendersSub: 'ಟೆಂಡರ್ ಬಿಡ್ಡುಗಳ ನೇರ ಮೇಲ್ವಿಚಾರಣೆ ಮತ್ತು ಸ್ವಯಂಚಾಲಿತ ವಿಶ್ಲೇಷಣೆ.',
    bidsUnderScrutiny: 'ಪರಿಶೀಲನೆಯಲ್ಲಿರುವ ಬಿಡ್ಡುಗಳು',
    aiScannedBids: 'AI ಸ್ಕ್ಯಾನ್ ಮಾಡಿದ ಬಿಡ್ಡುಗಳು',
    tenderRefNo: 'ಟೆಂಡರ್ ಉಲ್ಲೇಖ ಸಂಖ್ಯೆ',
    description: 'ವಿವರಣೆ',
    bidders: 'ಬಿಡ್ಡುದಾರರು',
    aiScrutinyStatus: 'AI ಪರಿಶೀಲನೆ ಸ್ಥಿತಿ',
    action: 'ಕ್ರಮ',
    compareBiddersBtn: 'ಬಿಡ್ಡುದಾರರನ್ನು ಹೋಲಿಸಿ >',
    comparativeScrutiny: 'ತುಲನಾತ್ಮಕ ಬಿಡ್ಡುದಾರರ ಪರಿಶೀಲನೆ',
    rankBidderName: 'ಶ್ರೇಣಿ / ಬಿಡ್ಡುದಾರರ ಹೆಸರು',
    complianceScore: 'ಅನುಸರಣೆ ಸ್ಕೋರ್',
    riskLevel: 'ಅಪಾಯ ಮಟ್ಟ',
    statutoryParity: 'ಶಾಸನಬದ್ಧ ಹೊಂದಾಣಿಕೆ',
    localContent: 'ಮೇಕ್ ಇನ್ ಇಂಡಿಯಾ ಸ್ಥಳೀಯ ವಿಷಯ',
    detailAudit: 'ವಿವರವಾದ ಆಡಿಟ್',
    lowRisk: 'ಕಡಿಮೆ (LOW)',
    mediumRisk: 'ಮಧ್ಯಮ (MEDIUM)',
    highRisk: 'ಹೆಚ್ಚು (HIGH)',
    backToTenders: '< ಟೆಂಡರ್‌ಗಳಿಗೆ ಹಿಂತಿರುಗಿ',
    backToComparison: '< ಹೋಲಿಕೆಗೆ ಹಿಂತಿರುಗಿ',
    backToDetail: '< ವಿವರಗಳಿಗೆ ಹಿಂತಿರುಗಿ',
    backToScrutiny: '< ಪರಿಶೀಲನೆಗೆ ಹಿಂತಿರುಗಿ',
    statutoryVerification: 'ಶಾಸನಬದ್ಧ ಪರಿಶೀಲನೆ',
    tenderVerification: 'ಟೆಂಡರ್ ನಿರ್ದಿಷ್ಟ ಪರಿಶೀಲನೆ',
    inspect: 'ಪರಿಶೀಲಿಸಿ',
    explainableRisk: 'ವಿವರಿಸಬಹುದಾದ ಅಪಾಯ ಮತ್ತು ಅನುಸರಣೆ ಸ್ಕೋರ್',
    trafficLightTier: 'ಟ್ರಾಫಿಕ್ ಲೈಟ್ ಹಂತ',
    factor: 'ಅಂಶ',
    weight: 'ನಿಗದಿಪಡಿಸಿದ ತೂಕ',
    result: 'ಫಲಿತಾಂಶ',
    verdict: 'ತೀರ್ಪು',
    auditTrailTitle: 'ಸಂಪೂರ್ಣ ಆಡಿಟ್ ಟ್ರಯಲ್ ಮತ್ತು ಅಧಿಕೃತ ಅನುಮೋದನೆ ಗೇಟ್',
    verificationTimeline: 'ಪರಿಶೀಲನೆ ಕಾಲಾವಧಿ',
    auditTrailTable: 'ಆಡಿಟ್ ಟ್ರಯಲ್ ಕೋಷ್ಟಕ',
    timestamp: 'ಸಮಯ',
    check: 'ತಪಾಸಣೆ',
    source: 'ಮೂಲ',
    evidence: 'ಸಾಕ್ಷಿ',
    performedBy: 'ನಿರ್ವಹಿಸಿದವರು',
    finalDecision: 'ಅಂತಿಮ ತೀರ್ಮಾನ — ಖರೀದಿ ಅಧಿಕಾರಿ',
    committeeRemarks: 'ಅಧಿಕೃತ ಸಮಿತಿ ಪರಿಶೀಲನಾ ಟಿಪ್ಪಣಿಗಳು',
    approveQualify: 'ಅನುಮೋದಿಸಿ / ಅರ್ಹತೆ ಪಡೆದಿದೆ',
    sendClarification: 'ಸ್ಪಷ್ಟೀಕರಣಕ್ಕಾಗಿ ಕಳುಹಿಸಿ',
    rejectDisqualify: 'ತಿರಸ್ಕರಿಸಿ / ಅನರ್ಹತೆ',
    exportDossier: 'ಆಡಿಟ್ ದಾಖಲೆಯನ್ನು ರಫ್ತು ಮಾಡಿ (.json)',
    uploadMissing: 'ಕಾಣೆಯಾದ ದಾಖಲೆಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    runAiExtraction: 'AI ಹೊರತೆಗೆಯುವಿಕೆ & ಪರಿಶೀಲನೆಯನ್ನು ಚಲಾಯಿಸಿ',
    signSubmitBid: 'ಸಹಿ ಮಾಡಿ ಬಿಡ್ ಸಲ್ಲಿಸಿ',
    updateInfo: 'ಮಾಹಿತಿಯನ್ನು ನವೀಕರಿಸಿ ಮತ್ತು ಮರುಪರಿಶೀಲಿಸಿ',
    enterArn: 'ಮಾನ್ಯವಾದ GSTR-3B ARN ನಮೂದಿಸಿ',
    ready: 'ಸಿದ್ಧವಾಗಿದೆ',
    attentionReq: 'ಗಮನ ಅಗತ್ಯವಿದೆ',
    portalStatus: 'ಪೋರ್ಟಲ್ ಪರಿಶೀಲನೆ ಸ್ಥಿತಿ (ನೇರ ಶಾಸನಬದ್ಧ APIಗಳು)',
  },
  ml: {
    govIndia: 'ഭാരത സർക്കാർ',
    ministry: 'വാണിജ്യ വ്യവസായ മന്ത്രാലയം',
    portalTagline: 'ദേശീയ പബ്ലിക് പ്രൊക്യുർമെന്റ് പോർട്ടൽ',
    skipToMain: 'പ്രധാന ഉള്ളടക്കത്തിലേക്ക് പോകുക',
    raiseTicket: 'ടിക്കറ്റ് സമർപ്പിക്കുക',
    needHelp: 'സഹായം ആവശ്യമുണ്ടോ ?',
    fontSize: 'ഫോണ്ട് വലിപ്പം',
    darkMode: 'ഡാർക്ക് മോഡ്',
    lightMode: 'ലൈറ്റ് മോഡ്',
    gemTitle: 'ഗവൺമെന്റ് ഇ മാർക്കറ്റ്‌പ്ലേസ്',
    gemMotto: 'കാര്യക്ഷമമായ • സുതാര്യമായ • സമഗ്രമായ',
    searchPlaceholder: 'GeM-ൽ എന്തെങ്കിലും തിരയുകയാണോ?',
    products: 'ഉൽപ്പന്നങ്ങൾ',
    services: 'സേവനങ്ങൾ',
    content: 'ഉള്ളടക്കം',
    courses: 'പരിശീലന കോഴ്സുകൾ',
    forwardAuction: 'ഫോർവേഡ് ലേലം',
    bids: 'ടെണ്ടറുകൾ',
    signUp: 'സൈൻ അപ്പ്',
    login: 'ലോഗിൻ',
    aiEngine: '⚡ AI നിയമപരമായ എഞ്ചിൻ',
    categories: 'വിഭാഗങ്ങൾ',
    home: 'ഹോം',
    features: 'സവിശേഷതകളും നേട്ടങ്ങളും',
    sellerOnGem: 'GeM-ൽ വിൽപ്പനക്കാരൻ',
    viewContracts: 'കരാറുകൾ കാണുക',
    cppp: 'CPPP',
    heroDecade: 'വിശ്വാസത്തിന്റെയും പരിവർത്തനത്തിന്റെയും',
    heroDecadeSub: 'പതിറ്റാണ്ട്',
    heroMotto: 'അനന്ത സാധ്യതകളുടെ പതിറ്റാണ്ട്',
    heroCelebrate: 'പുതിയ അവസരങ്ങൾക്ക് ചിറകുനൽകിയ പതിറ്റാണ്ടിന്റെ ആഘോഷം',
    heroSub2: 'ഈ ചരിത്രപരമായ മാറ്റത്തിൽ പങ്കാളിയാകൂ',
    askGemmy: 'GeMMy-യോട് ചോദിക്കൂ',
    askGemmySub: '(AI പിന്തുണയോടെ)',
    sellerDesk: 'വിൽപ്പനക്കാരുടെ കംപ്ലയൻസ് ഡെസ്ക്',
    officerPortal: 'പർച്ചേസ് ഓഫീസർ പോർട്ടൽ',
    gmv: 'ആകെ വ്യാപാര മൂല്യം',
    ordersProcessed: 'പൂർത്തിയാക്കിയ ഓർഡറുകൾ',
    registeredSellers: 'രജിസ്റ്റർ ചെയ്ത വിൽപ്പനക്കാർ',
    primaryBuyers: 'പരിശോധിച്ച വാങ്ങുന്നവർ',
    vocalForLocal: '#vocalforlocal',
    gemOutlets: 'GeM ഔട്ട്ലെറ്റ് സ്റ്റോറുകൾ',
    popularProducts: 'ജനപ്രിയ ഉൽപ്പന്ന വിഭാഗങ്ങൾ',
    popularServices: 'ജനപ്രിയ സേവന വിഭാഗങ്ങൾ',
    whyChooseGem: 'എന്തുകൊണ്ട് GeM തിരഞ്ഞെടുക്കണം',
    customersSpeak: 'ഉപഭോക്തൃ പ്രതികരണങ്ങൾ',
    exploreMarket: 'വിപണി പര്യവേക്ഷണം ചെയ്യുക',
    viewAllServices: 'എല്ലാ സേവനങ്ങളും കാണുക',
    footerRuleNotice: 'നിയമപരമായ അനുസരണവും GFR ചട്ടം 144(xi) പരിശോധനാ ഗേറ്റ്‌വേയും',
    footerCopyright: '© 2026 ഗവൺമെന്റ് ഇ മാർക്കറ്റ്‌പ്ലേസ് (GeM). സ്മാർട്ട് ഇന്ത്യ ഹാക്കത്തോൺ (SIH26100).',
    activeTenders: 'സജീവ ടെണ്ടറുകൾ',
    compareBidders: 'ബിഡ്ഡർമാരെ താരതമ്യം ചെയ്യുക',
    deepAudit: 'ഡീപ് ഓഡിറ്റ്',
    findingsRisk: 'കണ്ടെത്തലുകളും അപകടസാധ്യതയും',
    auditSignOff: 'ഓഡിറ്റും അന്തിമ തീരുമാനവും',
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    officerConsole: 'പർച്ചേസ് ഓഫീസർ പരിശോധനാ കൺസോൾ',
    sellerPortal: 'വിൽപ്പനക്കാരുടെ കംപ്ലയൻസ് പോർട്ടൽ',
    logout: 'ലോഗൗട്ട്',
    gemHome: 'GeM ഹോം',
    close: 'അടയ്ക്കുക',
    submit: 'സമർപ്പിക്കുക',
    cancel: 'റദ്ദാക്കുക',
    readiness: 'കംപ്ലയൻസ് തയ്യാറെടുപ്പ്',
    verified: 'പരിശോധിച്ചുറപ്പിച്ചു',
    pending: 'തീർപ്പുകൽപ്പിക്കാത്തത്',
    issues: 'പ്രശ്നങ്ങൾ',
    discrepancies: 'പൊരുത്തക്കേടുകൾ കണ്ടെത്തി',
    activeProcurementTenders: 'സജീവ പർച്ചേസ് ടെണ്ടറുകൾ',
    activeTendersSub: 'ടെണ്ടർ ബിഡ്ഡുകളുടെ തത്സമയ നിരീക്ഷണവും ഓട്ടോമേറ്റഡ് വിശകലനവും.',
    bidsUnderScrutiny: 'പരിശോധനയിലുള്ള ബിഡ്ഡുകൾ',
    aiScannedBids: 'AI സ്കാൻ ചെയ്ത ബിഡ്ഡുകൾ',
    tenderRefNo: 'ടെണ്ടർ റഫറൻസ് നമ്പർ',
    description: 'വിവരണം',
    bidders: 'ബിഡ്ഡർമാർ',
    aiScrutinyStatus: 'AI പരിശോധനാ നില',
    action: 'നടപടി',
    compareBiddersBtn: 'ബിഡ്ഡർമാരെ താരതമ്യം ചെയ്യുക >',
    comparativeScrutiny: 'താരതമ്യ ബിഡ്ഡർ പരിശോധന',
    rankBidderName: 'റാങ്ക് / ബിഡ്ഡർ പേര്',
    complianceScore: 'കംപ്ലയൻസ് സ്കോർ',
    riskLevel: 'റിസ്ക് ലെവൽ',
    statutoryParity: 'നിയമാനുസൃത അനുയോജ്യത',
    localContent: 'മേക്ക് ഇൻ ഇന്ത്യ ലോക്കൽ കണ്ടന്റ്',
    detailAudit: 'വിശദമായ ഓഡിറ്റ്',
    lowRisk: 'കുറഞ്ഞ (LOW)',
    mediumRisk: 'ഇടത്തരം (MEDIUM)',
    highRisk: 'ഉയർന്ന (HIGH)',
    backToTenders: '< ടെണ്ടറുകളിലേക്ക് മടങ്ങുക',
    backToComparison: '< താരതമ്യത്തിലേക്ക് മടങ്ങുക',
    backToDetail: '< വിശദാംശങ്ങളിലേക്ക് മടങ്ങുക',
    backToScrutiny: '< പരിശോധനയിലേക്ക് മടങ്ങുക',
    statutoryVerification: 'നിയമാനുസൃത പരിശോധന',
    tenderVerification: 'ടെണ്ടർ നിർദ്ദിഷ്ട പരിശോധന',
    inspect: 'പരിശോധിക്കുക',
    explainableRisk: 'വിശദീകരിക്കാവുന്ന റിസ്ക് & കംപ്ലയൻസ് സ്കോർ',
    trafficLightTier: 'ട്രാഫിക് ലൈറ്റ് തലം',
    factor: 'ഘടകം',
    weight: 'നൽകിയിട്ടുള്ള വെയിറ്റേജ്',
    result: 'ഫലം',
    verdict: 'തീർപ്പ്',
    auditTrailTitle: 'പൂർണ്ണ ഓഡിറ്റ് ട്രയലും ഔദ്യോഗിക അംഗീകാര ഗേറ്റും',
    verificationTimeline: 'പരിശോധനാ സമയക്രമം',
    auditTrailTable: 'ഓഡിറ്റ് ട്രയൽ പട്ടിക',
    timestamp: 'സമയം',
    check: 'പരിശോധന',
    source: 'ഉറവിടം',
    evidence: 'തെളിവ്',
    performedBy: 'നിർവ്വഹിച്ചത്',
    finalDecision: 'അന്തിമ തീരുമാനം — പർച്ചേസ് ഓഫീസർ',
    committeeRemarks: 'കമ്മിറ്റി പരിശോധനാ പരാമർശങ്ങൾ',
    approveQualify: 'അംഗീകരിക്കുക / യോഗ്യത നേടി',
    sendClarification: 'വ്യക്തതയ്ക്കായി അയയ്ക്കുക',
    rejectDisqualify: 'നിരസിക്കുക / അയോഗ്യത',
    exportDossier: 'ഓഡിറ്റ് ഡോസിയർ എക്സ്പോർട്ട് ചെയ്യുക (.json)',
    uploadMissing: 'വിട്ടുപോയ പ്രമാണം അപ്‌ലോഡ് ചെയ്യുക',
    runAiExtraction: 'AI എക്സ്ട്രാക്ഷനും പരിശോധനയും നടത്തുക',
    signSubmitBid: 'സൈൻ ചെയ്ത് ബിഡ് സമർപ്പിക്കുക',
    updateInfo: 'വിവരങ്ങൾ അപ്ഡേറ്റ് ചെയ്ത് വീണ്ടും പരിശോധിക്കുക',
    enterArn: 'സാധുവായ GSTR-3B ARN നൽകുക',
    ready: 'തയ്യാറാണ്',
    attentionReq: 'ശ്രദ്ധ ആവശ്യമാണ്',
    portalStatus: 'പോർട്ടൽ പരിശോധനാ നില (തത്സമയ നിയമപരമായ APIകൾ)',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  currentOption: LanguageOption;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>('en');

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('gem_app_lang', lang);
  };

  useEffect(() => {
    const saved = localStorage.getItem('gem_app_lang') as LanguageCode;
    if (saved && TRANSLATIONS[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const currentOption =
    SUPPORTED_LANGUAGES.find((opt) => opt.code === language) || SUPPORTED_LANGUAGES[0];

  const t = (key: string): string => {
    const dict = TRANSLATIONS[language] || TRANSLATIONS.en;
    return dict[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, currentOption, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
